export const studentsDummy = [
  // Kelas IV-A
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345678,
    nama: "Muhammad Raihan",
    alamat: "Lowokwaru, Malang",
    kelas: "IV-A",
    wali_siswa: "Ahmad Subarjo",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345679,
    nama: "Aisyah Nayla",
    alamat: "Blimbing, Malang",
    kelas: "IV-A",
    wali_siswa: "Bambang Wijaya",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345680,
    nama: "Fatih Rizky",
    alamat: "Sukun, Malang",
    kelas: "IV-A",
    wali_siswa: "Heri Santoso",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345681,
    nama: "Khadijah Azzahra",
    alamat: "Klojen, Malang",
    kelas: "IV-A",
    wali_siswa: "Slamet Rahardjo",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345682,
    nama: "Daffa Ibrahim",
    alamat: "Kedungkandang, Malang",
    kelas: "IV-A",
    wali_siswa: "Mulyono",
  },

  // Kelas IV-B
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345683,
    nama: "Zidni Ilman",
    alamat: "Singosari, Malang",
    kelas: "IV-B",
    wali_siswa: "Agus Prayitno",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345684,
    nama: "Nabila Syahputri",
    alamat: "Dau, Malang",
    kelas: "IV-B",
    wali_siswa: "Rudi Hermawan",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345685,
    nama: "Rayhan Malik",
    alamat: "Pakis, Malang",
    kelas: "IV-B",
    wali_siswa: "Joko Susilo",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345686,
    nama: "Siti Rahma",
    alamat: "Batu, Malang",
    kelas: "IV-B",
    wali_siswa: "Edi Sudradjat",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345687,
    nama: "Amiruddin",
    alamat: "Kepanjen, Malang",
    kelas: "IV-B",
    wali_siswa: "Arifin",
  },

  // Kelas V-A
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345688,
    nama: "Ali Zainal",
    alamat: "Lowokwaru, Malang",
    kelas: "V-A",
    wali_siswa: "Lukman Hakim",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345689,
    nama: "Fatima Zahra",
    alamat: "Karangploso, Malang",
    kelas: "V-A",
    wali_siswa: "Syarifuddin",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345690,
    nama: "Yusuf Al-Ghifari",
    alamat: "Lawang, Malang",
    kelas: "V-A",
    wali_siswa: "Hendra Wijaya",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345691,
    nama: "Zahra Amelia",
    alamat: "Blimbing, Malang",
    kelas: "V-A",
    wali_siswa: "Sugeng Riyadi",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345692,
    nama: "Fajar Shodiq",
    alamat: "Sukun, Malang",
    kelas: "V-A",
    wali_siswa: "Eko Prasetyo",
  },

  // Kelas V-B
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345693,
    nama: "Bilal Ramadhan",
    alamat: "Tumpang, Malang",
    kelas: "V-B",
    wali_siswa: "Mansur",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345694,
    nama: "Safira Putri",
    alamat: "Wagir, Malang",
    kelas: "V-B",
    wali_siswa: "Toto Suprapto",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345695,
    nama: "Hamzah Fansuri",
    alamat: "Tajinan, Malang",
    kelas: "V-B",
    wali_siswa: "Rizal Hamzah",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345696,
    nama: "Maryanti",
    alamat: "Pakisaji, Malang",
    kelas: "V-B",
    wali_siswa: "Gatot Subroto",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345697,
    nama: "Lukmanul Hakim",
    alamat: "Klojen, Malang",
    kelas: "V-B",
    wali_siswa: "M. Ridwan",
  },

  // Kelas VI-A
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345698,
    nama: "Ahmad Fulan",
    alamat: "Lowokwaru, Malang",
    kelas: "VI-A",
    wali_siswa: "Lilis Suryani",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345699,
    nama: "Siti Aminah",
    alamat: "Kedungkandang, Malang",
    kelas: "VI-A",
    wali_siswa: "Supardi",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345700,
    nama: "Omar Mukhtar",
    alamat: "Singosari, Malang",
    kelas: "VI-A",
    wali_siswa: "Farhan Effendi",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345701,
    nama: "Aisyah Humaira",
    alamat: "Dau, Malang",
    kelas: "VI-A",
    wali_siswa: "Zainal Arifin",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345702,
    nama: "Khalid Basalamah",
    alamat: "Batu, Malang",
    kelas: "VI-A",
    wali_siswa: "Syaifullah",
  },

  // Kelas VI-B
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345703,
    nama: "Thariq Ziyad",
    alamat: "Blimbing, Malang",
    kelas: "VI-B",
    wali_siswa: "Iwan Setiawan",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345704,
    nama: "Nabila Asy-Syifa",
    alamat: "Sukun, Malang",
    kelas: "VI-B",
    wali_siswa: "Dedi Suhendra",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345705,
    nama: "Hasan Basri",
    alamat: "Kepanjen, Malang",
    kelas: "VI-B",
    wali_siswa: "Umar Bakri",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345706,
    nama: "Tsabita Kamila",
    alamat: "Karangploso, Malang",
    kelas: "VI-B",
    wali_siswa: "Budi Santoso",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    nis: 12345707,
    nama: "Abdullah",
    alamat: "Lawang, Malang",
    kelas: "VI-B",
    wali_siswa: "Anwar Sadad",
  },
];
