export const usersDummy = [
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Ahmad Fulan",
    email: "fulan@mail.com",
    no_telp: "+628123456789",
    role: "super_admin",
    last_login: "2",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Siti Aminah",
    email: "siti.aminah@mail.com",
    no_telp: "+628123456790",
    role: "super_admin",
    last_login: "1",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Budi Santoso",
    email: "budi.santoso@mail.com",
    no_telp: "+628123456791",
    role: "super_admin",
    last_login: "5",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Hendra Wijaya",
    email: "hendra.w@mail.com",
    no_telp: "+628123456792",
    role: "direktur",
    last_login: "3",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Rinawati",
    email: "rinawati@mail.com",
    no_telp: "+628123456793",
    role: "direktur",
    last_login: "2",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Agus Setiawan",
    email: "agus.s@mail.com",
    no_telp: "+628123456794",
    role: "direktur",
    last_login: "4",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Dewi Lestari",
    email: "dewi.l@mail.com",
    no_telp: "+628123456795",
    role: "direktur",
    last_login: "1",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Fahmi Idris",
    email: "fahmi.idris@mail.com",
    no_telp: "+628123456796",
    role: "direktur",
    last_login: "7",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Muhammad Rizky",
    email: "m.rizky@mail.com",
    no_telp: "+628123456797",
    role: "muhassin",
    last_login: "10",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Aisyah Humaira",
    email: "aisyah.h@mail.com",
    no_telp: "+628123456798",
    role: "muhaffidz",
    last_login: "2",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Yusuf Mansur",
    email: "yusuf.m@mail.com",
    no_telp: "+628123456799",
    role: "muhassin",
    last_login: "6",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Khadijah Aliyah",
    email: "khadijah.a@mail.com",
    no_telp: "+628123456800",
    role: "muhaffidz",
    last_login: "3",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Andi Pratama",
    email: "andi.p@mail.com",
    no_telp: "+628123456801",
    role: "muhassin",
    last_login: "12",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Fatimah Zahra",
    email: "fatimah.z@mail.com",
    no_telp: "+628123456802",
    role: "muhaffidz",
    last_login: "1",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Rizal Hamzah",
    email: "rizal.h@mail.com",
    no_telp: "+628123456803",
    role: "muhassin",
    last_login: "8",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Zainab Az-Zahra",
    email: "zainab.z@mail.com",
    no_telp: "+628123456804",
    role: "muhaffidz",
    last_login: "5",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Lukman Hakim",
    email: "lukman.h@mail.com",
    no_telp: "+628123456805",
    role: "muhassin",
    last_login: "14",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Maryam Ulfa",
    email: "maryam.u@mail.com",
    no_telp: "+628123456806",
    role: "muhaffidz",
    last_login: "2",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Fajar Shidiq",
    email: "fajar.s@mail.com",
    no_telp: "+628123456807",
    role: "muhassin",
    last_login: "9",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Sarah Fauziah",
    email: "sarah.f@mail.com",
    no_telp: "+628123456808",
    role: "muhaffidz",
    last_login: "4",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Ibrahim Malik",
    email: "ibrahim.m@mail.com",
    no_telp: "+628123456809",
    role: "muhassin",
    last_login: "11",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Hajar Aswad",
    email: "hajar.a@mail.com",
    no_telp: "+628123456810",
    role: "muhaffidz",
    last_login: "6",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Ismail Basri",
    email: "ismail.b@mail.com",
    no_telp: "+628123456811",
    role: "muhassin",
    last_login: "3",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Safiyah Putri",
    email: "safiyah.p@mail.com",
    no_telp: "+628123456812",
    role: "muhaffidz",
    last_login: "7",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Yunus Alamsyah",
    email: "yunus.a@mail.com",
    no_telp: "+628123456813",
    role: "muhassin",
    last_login: "5",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Asiyah Jamil",
    email: "asiyah.j@mail.com",
    no_telp: "+628123456814",
    role: "muhaffidz",
    last_login: "1",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Tariq Ziyad",
    email: "tariq.z@mail.com",
    no_telp: "+628123456815",
    role: "muhassin",
    last_login: "15",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Bilqis Ratu",
    email: "bilqis.r@mail.com",
    no_telp: "+628123456816",
    role: "muhaffidz",
    last_login: "8",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Yahya Khalid",
    email: "yahya.k@mail.com",
    no_telp: "+628123456817",
    role: "muhassin",
    last_login: "4",
  },
  {
    profile_photo: "https://i.pravatar.cc/300",
    name: "Sumayyah binti Khayyat",
    email: "sumayyah.b@mail.com",
    no_telp: "+628123456818",
    role: "muhaffidz",
    last_login: "2",
  },
];
